

---
data_creation:
  data_name: try_fix_rotations # name of data file for the created data
  classes: 2 # Number of Classes to specify
  modals: # The different modal volumes to use
    - "t1"
    - "t1ce"
    - "t2"
    - "flair"
  bindings: # Binding dimensions
    height:
      - 56
      - 184
    width:
      - 56
      - 184
    pictures:
      - 13
      - 141
  raw_data_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\raw
  processed_data_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed
  data_split: # How to split the data, represented as decimals
    train: 0.8
    validation: 0.1
    testing: 0.1

---
training:
  experiment: test_bin_one # name of the experiment
  data_directory: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\test_binary_experiment\original
  epoch: 50 # epoch number
  batch: 32 # batch number
  output_size: # Output dimension for the model
    height: 128
    width: 128
  save_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model
  data_nature: original # What is the nature of the data (original for usual data)
  patience: 30 # number of epochs to use until to stop training_utils
  gradient_clipping: 3 # Gradient clipping value
  weight_decay: 0.001 # If using L2 weight regularization
  learning_metrics:
    - "accuracy"
    - "hausdorff"
    - "IoU"
  ilr: 0.0001
  augmentations:
    - vertical_flipping: 0.5
    - horizontal_flipping: 0.5
    - rotation:
          degree: 90
          probability: 0.5
    - random_crop: 10
  loss:
    Dice:
        coefficient: 0.5
    Focal:
        coefficient: 0.5
        alpha: 1
        gamma: 2
  optimizer: ADAM
  model:
    building_block:
      - conv2d
      - dropout
      - conv2d
      - batch_normalization
      - relu
    layers:
      - 64
      - 128
      - 256
    kernel: 3
    stride: 1
    max_pool: 2
    normalization: true
    dropout_rate: 0.5
  verbose_mode: true # Print epoch progress
  GPU: cuda
  selected_mri:
    t1ce: 1
    t2: 2
    flair: 3

---

testing:
  batch: 32
  metrics:
    - hausdorff
    - dice
  experiment_location: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model
  experiment_name: test_bin_one
  model_name: model.pth
  data_location:  D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed
  data_name: test_binary_experiment
  selected_mri:
    t1ce: 1
    t2: 2
    flair: 3
  GPU: cuda

---

graphing:
  single_images: null
  experiments:
    - test_bin_one:
        model_name: model.pth
        directory_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model
        input_image_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed\test_binary_experiment\original\inputs\testing
        input_seg_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed\test_binary_experiment\original\targets\testing
        data_info:
          selected_mri:
            t1ce: 1
            t2: 2
            flair: 3
          classes: 2
          batch: 50
          instance: 15
          mri_volume: 3
  learning_metrics:
    - Loss_results:
        recordings:
          validation_loss: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model\test_bin_one\validation\Graph\loss.pkl
          training_loss: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model\test_bin_one\training\Graph\loss.pkl
        y_label: Loss Results
    - Hausdorff_Results:
        recordings:
          validation_loss: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model\test_bin_one\validation\Graph\hausdorff.pkl
          training_loss: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model\test_bin_one\training\Graph\hausdorff.pkl
        y_label: Hausdorff Results
#  images:
#    rotation:
#        location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\rotations90\inputs\training_utils\epoch_1.pt
#        classes: 2
#        colour: false
#        mri_volume: 2
#        batch: 80
#    horizontal_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\horizontal_flip\inputs\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      mri_volume: 2
#      batch: 80
#    vertical_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\vertical_flip\inputs\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      mri_volume: 2
#      batch: 80
#  masks:
#    rotation:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\rotations90\targets\training_utils\epoch_1.pt
#      classes: 2
#      colour: false
#      batch: 80
#    horizontal_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\horizontal_flip\targets\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      batch: 80
#    vertical_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\vertical_flip\targets\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      batch: 80


