

---
data_creation:
  data_name: 4_channel_data # name of data file for the created data
  classes: 2 # Number of Classes to specify
  modals: # The different modal volumes to use
    - "t1"
    - "t1ce"
    - "t2"
    - "flair"
  bindings: # Binding dimensions
    height:
      - 56
      - 184
    width:
      - 56
      - 184
    pictures:
      - 13
      - 141
  raw_data_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\raw
  processed_data_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed
  data_split: # How to split the data, represented as decimals
    train: 0.8
    validation: 0.1
    testing: 0.1

---
training:
  experiment: UNet_results # name of the experiment
  data_directory: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed\test_binary_experiment\original
  load: true
  epoch: 10 # epoch number
  batch: 32 # batch number
  output_size: # Output dimension for the model
    height: 128
    width: 128
  save_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model
  patience: 5 # number of epochs to use until to stop training_utils
  gradient_clipping: 2 # Gradient clipping value
  weight_decay: 0.0001 # If using L2 weight regularization
  learning_metrics:
    - "IoU"
  ilr: 0.001
  augmentations:
    - vertical_flipping: 0.5
    - horizontal_flipping: 0.5
    - rotation: 90
  loss:
    "loss_coefficients":
      - 0.5
      - 0.5
    "focal_alpha": 1
    "focal_gamma": 1
  optimizer: ADAM
  model:
    building_block:
      - conv2d
      - dropout
      - conv2d
      - batch_normalization
      - relu
    layers:
      - 64
      - 128
      - 256
    kernel: 3
    stride: 1
    max_pool: 2
    normalization: true
    dropout_rate: 0.3
  verbose_mode: true # Print epoch progress
  GPU: MLDirect
  selected_mri:
    - 1
    - 2
    - 3
---
grid_search:
  experiment: test_grid_search # name of the experiment
  data_directory: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed\test_binary_experiment\standard_test
  epoch: # epoch numbers for experimentation
    - 1
  batch:  # batch number
    - 1
  output_size: # Output dimension for the model
    height: 128
    width: 128
  save_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model
  data_nature: original # What is the nature of the data (original for usual data)
  patience:  # number of epochs to use until to stop training_utils
    - 5
    - 10
    - 15
  gradient_clipping:  # Gradient clipping value
    - 1
    - 3
    - 5
    - 10
  weight_decay: # If using L2 weight regularization
    - 0.0001
    - 0.001
    - 0.01
  learning_metrics:
    - "accuracy"
    - "hausdorff"
    - "IoU"
  ilr:
    - 0.0001
    - 0.001
    - 0.01
  augmentations:
    - vertical_flipping: 0.5
    - horizontal_flipping: 0.5
    - rotation: 90
  loss:
    coefficients:
      - [0.5, 0.5]
      - [1.0, 0]
      - [0, 1.0]
      - [0.7, 0.3]
      - [0.3, 0.7]
    Dice: True
    Focal:
        alpha:
          - 0.5
          - 1
          - 1.5
          - 2
          - 3
        gamma:
          - 0.5
          - 1
          - 1.5
          - 2
          - 3
  optimizer: ADAM
  model:
    building_block:
      - conv2d
      - dropout
      - conv2d
      - batch_normalization
      - relu
    layers:
      - [64, 128, 256]
      - [128, 256, 512]
    kernel: 3
    stride: 1
    max_pool: 2
    normalization: true
    dropout_rate:
      - 0
      - 0.25
      - 0.5
      - 0.75
  verbose_mode: true # Print epoch progress
  GPU: null
  selected_mri:
    order:
      t1: 0
      t1ce: 1
      t2: 2
      flair: 3
    selected:
      - 1
      - 2
      - 3
    version: "combination"

---

testing:
  batch: 32
  metrics:
    - hausdorff
    - dice
  experiment_location: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model
  experiment_name: test_bin_one
  model_name: model.pth
  data_location:  D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed
  data_name: test_binary_experiment
  selected_mri:
    t1ce: 1
    t2: 2
    flair: 3
  GPU: cuda

---

graphing:
  single_images: null
  experiments: null
#    - test_bin_one:
#        model_name: model.pth
#        directory_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model
#        input_image_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed\test_binary_experiment\original\inputs\testing
#        input_seg_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed\test_binary_experiment\original\targets\testing
#        data_info:
#          selected_mri:
#            t1ce: 1
#            t2: 2
#            flair: 3
#          classes: 2
#          batch: 50
#          instance: 15
#          mri_volume: 3
  learning_metrics:
    - Loss_results:
        recordings:
          validation_loss: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model\test_epoch\interesting_valid\validation\Graph\loss.pkl
          training_loss: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model\test_epoch\interesting_training\training\Graph\loss.pkl
        y_label: Loss Results
    - Hausdorff_Results:
        recordings:
          validation_loss: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model\test_epoch\interesting_valid\validation\Graph\hausdorff.pkl
          training_loss: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model\test_epoch\interesting_training\training\Graph\hausdorff.pkl
        y_label: Hausdorff Results
#  images:
#    rotation:
#        location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\rotations90\inputs\training_utils\epoch_1.pt
#        classes: 2
#        colour: false
#        mri_volume: 2
#        batch: 80
#    horizontal_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\horizontal_flip\inputs\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      mri_volume: 2
#      batch: 80
#    vertical_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\vertical_flip\inputs\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      mri_volume: 2
#      batch: 80
#  masks:
#    rotation:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\rotations90\targets\training_utils\epoch_1.pt
#      classes: 2
#      colour: false
#      batch: 80
#    horizontal_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\horizontal_flip\targets\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      batch: 80
#    vertical_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\vertical_flip\targets\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      batch: 80


