

---
data_creation:
  data_name: test_binary_experiment # name of data file for the created data
  classes: 2 # Number of Classes to specify
  modals: # The different modal volumes to use
    - "flair"
    - "t2"
    - "t1ce"
  bindings: # Binding dimensions
    height:
      - 56
      - 184
    width:
      - 56
      - 184
    pictures:
      - 13
      - 141
  raw_data_path: "C:\\Users\\james\\Uni_Projects\\CS4_CompNeuroProj\\src\\data\\raw"
  input_data_path: "C:\\Users\\james\\Uni_Projects\\CS4_CompNeuroProj\\src\\data\\processed"
  target_data_path: "C:\\Users\\james\\Uni_Projects\\CS4_CompNeuroProj\\src\\data\\processed"
  data_split: # How to split the data, represented as decimals
    train: 0.8
    validation: 0.1
    testing: 0.1
  data_augmentation:
#    - rotations: null
#        - 90
    - flipping:
        - vertical
        - horizontal
  special_operations:
    permutate_volumes: false # Create data sets for each MRI mode permutation
    super_permutate: false # For each mri, do every single combination for each volume
    data_augmentation: false # Include specified data augmentation
---

training:
  experiment: test_bin_one # name of the experiment
  epoch: 100 # epoch number
  batch: 64 # batch number
  output_size: # Output dimension for the model
    height: 128
    width: 128
  save_path: "C:\\Users\\james\\Uni_Projects\\CS4_CompNeuroProj\\src\\experiments\\saved_model"
  data_nature: original # What is the nature of the data (original for usual data)
  patience: 30 # number of epochs to use until to stop training
  gradient_clipping: 3 # Gradient clipping value
  weight_decay: 0.001 # If using weight regularization
  learning_metrics:
    - "accuracy"
    - "hausdorff"
    - "IoU"
  ilr: 0.001
  loss_function: Dice
  optimizer: ADAM
  alg_set_up:
    name: UNet
    parameters:
      building_block:
        - conv2d
        - conv2d
        - relu
      stacks:
        - 16
        - 32
        - 64
      kernel: 3
      stride: 1
      max_pool: 2
  special_operations:
    continually_save_model: false # Continually save the model at the specified data locations
    create_data: false # Create data with the specified data creation section
    verbose_mode: true # Print epoch progress

---

testing:
  metrics:
    - hausdorff
    - dice_loss
  experiment_location: "C:\\Users\\james\\Uni_Projects\\CS4_CompNeuroProj\\src\\experiments\\saved_model\\fix_stuff"
  model_name: model.pth
  testing_data_location: "C:\\Users\\james\\Uni_Projects\\CS4_CompNeuroProj\\src\\data\\processed\\"
  experiment_name: "main_binary_experiment"
---

graphing:
  images: null
  masks: null
#  images:
#    rotation:
#        location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\rotations90\inputs\training\epoch_1.pt
#        classes: 2
#        colour: false
#        mri_volume: 2
#        batch: 80
#    horizontal_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\horizontal_flip\inputs\training\epoch_1.pt
#      classes: binary
#      colour: false
#      mri_volume: 2
#      batch: 80
#    vertical_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\vertical_flip\inputs\training\epoch_1.pt
#      classes: binary
#      colour: false
#      mri_volume: 2
#      batch: 80
#  masks:
#    rotation:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\rotations90\targets\training\epoch_1.pt
#      classes: 2
#      colour: false
#      batch: 80
#    horizontal_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\horizontal_flip\targets\training\epoch_1.pt
#      classes: binary
#      colour: false
#      batch: 80
#    vertical_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\vertical_flip\targets\training\epoch_1.pt
#      classes: binary
#      colour: false
#      batch: 80
  learning_metrics:
      - Loss_results:
          recordings:
            validation_loss: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\experiments\saved_model\test_bin_one\validation\Graph\loss.pkl
            training_loss: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\experiments\saved_model\test_bin_one\training\Graph\loss.pkl
          y_label: Loss Results


#  loss_loc: Graph\\train_loss.pkl
#  data_input_loc: "C:\\Users\\james\\Uni_Projects\\CS4_CompNeuroProj\\src\\data\\processed\\standard_experiment"
#  exp_loc: inputs\\epoch_121.pt
#  label_loc: targets\\epoch_121.pt
#  segmentation_res: true
#  model_loss: true
#  hd: true
#  iou: true
#  accuracy: true
