

---
data_creation:
  data_name: test_binary_experiment # name of data file for the created data
  classes: 2 # Number of Classes to specify
  modals: # The different modal volumes to use
    - "t1"
    - "t1ce"
    - "t2"
    - "flair"
  bindings: # Binding dimensions
    height:
      - 56
      - 184
    width:
      - 56
      - 184
    pictures:
      - 13
      - 141
  raw_data_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\raw
  processed_data_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\data\processed
  data_split: # How to split the data, represented as decimals
    train: 0.8
    validation: 0.1
    testing: 0.1
  data_augmentation:
    - flipping:
        - vertical
        - horizontal
---
training:
  experiment: test_bin_one # name of the experiment
  epoch: 100 # epoch number
  batch: 64 # batch number
  output_size: # Output dimension for the model
    height: 128
    width: 128
  save_path: D:\Users\James\Code_Projects\CS4_CompNeuroProj\CS4_CompNeuroProj\src\experiments\saved_model
  data_nature: original # What is the nature of the data (original for usual data)
  patience: 30 # number of epochs to use until to stop training_utils
  gradient_clipping: 3 # Gradient clipping value
  weight_decay: 0.001 # If using weight regularization
  learning_metrics:
    - "accuracy"
    - "hausdorff"
    - "IoU"
  ilr: 0.001
  loss_function: Dice
  optimizer: ADAM
  alg_set_up:
    name: UNet
    parameters:
      building_block:
        - conv2d
        - conv2d
        - relu
      stacks:
        - 16
        - 32
        - 64
      kernel: 3
      stride: 1
      max_pool: 2
  verbose_mode: true # Print epoch progress
  selected_mri:
    t1ce: 1
    t2: 2
    flair: 3

---

testing:
  batch: 64
  metrics:
    - hausdorff
    - dice_loss
  experiment_location: "C:\\Users\\james\\Uni_Projects\\CS4_CompNeuroProj\\src\\experiments\\saved_model"
  experiment_name: "main_binary_experiment"
  model_name: model.pth
  data_location: "C:\\Users\\james\\Uni_Projects\\CS4_CompNeuroProj\\src\\data\\processed\\"
  data_name: "test_binary_experiment"

---

graphing:
  images: null
  masks: null
#  images:
#    rotation:
#        location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\rotations90\inputs\training_utils\epoch_1.pt
#        classes: 2
#        colour: false
#        mri_volume: 2
#        batch: 80
#    horizontal_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\horizontal_flip\inputs\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      mri_volume: 2
#      batch: 80
#    vertical_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\vertical_flip\inputs\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      mri_volume: 2
#      batch: 80
#  masks:
#    rotation:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\rotations90\targets\training_utils\epoch_1.pt
#      classes: 2
#      colour: false
#      batch: 80
#    horizontal_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\horizontal_flip\targets\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      batch: 80
#    vertical_flip:
#      location: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\data\processed\main_binary_experiment\vertical_flip\targets\training_utils\epoch_1.pt
#      classes: binary
#      colour: false
#      batch: 80
  learning_metrics:
      - Loss_results:
          recordings:
            validation_loss: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\experiments\saved_model\test_bin_one\validation\Graph\loss.pkl
            training_loss: C:\Users\james\Uni_Projects\CS4_CompNeuroProj\src\experiments\saved_model\test_bin_one\training\Graph\loss.pkl
          y_label: Loss Results

